### ISSUE TITLE
Add Popup on click

### ISSUE THREAD

**Issue by codingjoe** [bewithjonam/mapboxgl-spiderifier#10] opened 2020-08-11 07:30 UTC
Hi there,

Great package, just what I was looking for when upgrading from leavlet to Mapbox GL.
I am trying to get the popup over a spiderified marker to open on a click event and I can't get it to work.

I can't do this because the `container` is not a clickable element:
```javascript
    const spiderifier = new MapboxglSpiderifier(map, {
        customPin: true,
        initializeLeg: (spiderLeg) => {
          const popup = new mapboxgl.Popup({
            offset: MapboxglSpiderifier.popupOffsetForSpiderLeg(spiderLeg)
          })
          spiderLeg.mapboxMarker.setPopup(popup)
          spiderLeg.elements.container.addEventListener('click', () => { // I can make it work for mouseover, but click isn't trigger by a div
            console.debug(spiderLeg)
            popup.setHTML('<h1>TEST</h1>').addTo(map)
          })
        }
    )
```

For some reason I can't use the custom `onClick` callback to work as well.
```javascript
const spiderifier = new MapboxglSpiderifier(map, {
  customPin: true,
  initializeLeg: (spiderLeg) => {
    const popup = new mapboxgl.Popup({
      offset: MapboxglSpiderifier.popupOffsetForSpiderLeg(spiderLeg)
    })
    spiderLeg.mapboxMarker.setPopup(popup)
  },
  onClick: (e, spiderLeg) => {
    console.debug(spiderLeg)
    const popup = spiderLeg.mapboxMarker.getPopup()
    spiderLeg.mapboxMarker.setPopup(popup)
    popup.setHTML('<h1>TEST</h1>').addTo(map)
  }
})
```

I the click event in my console, but the popup is nowhere to be found on the screen.

If you happen to have a quick example for me on how to make popups work on a click on the spiderleg, that would help a lot.

Thanks a lot in advance!

Best,
Joe

**Comment by bewithjonam** [comment] 2020-08-12 07:11
In both your code snippets, add `spiderLeg.mapboxMarker.togglePopup()` after adding the popup to the map.

For some reason mapbox is closing the popups on a click event. Even when we pass `closeOnClick: false` to the popup.

First the click gets called for the marker, you attach the popup and the popup shows. The event bubbles up and gets called on the map which is the parent. And somehow the map is closing the popup. I am not sure about this hypothesis. I will investigate more about this.

In the mean time, Workaround is either toggle the popup as suggested. Or set the popup and addTo map in a setInterval, so that popup gets displayed after the click event is fully done.

```
onClick: (e, spiderLeg) => {
   ...
 
  setTimeout(() => {
      spiderLeg.mapboxMarker.setPopup(popup)
      popup.setHTML('<h1>TEST</h1>').addTo(map)
  }, 10);
}
```

**Comment by codingjoe** [comment] 2020-08-12 08:40
Hi @bewithjonam the tiny timeout works, thanks. I can't really use `moveenter` and `mouseleave` since I need people to interact with the popup. Also hover interactions are not the most user-friendly, especially since they are not available on mobile. Anyhow, works for now. Let me know if you find a better solution in the future. Best, Joe

**Closed as completed** 2020-10-28 06:36 UTC

**Comment by jottevanger** [comment] 2021-05-25 15:45
hugely relieved to find this discussion after a full day of trying to get to the bottom of this. I would rather solve it than ask for help from the maintainers but had finally reached that point, and then took a look at the closed issues and found this one. 
Please could I ask that either (a) this temporary solution is included in the documentation, because as @codingjoe points out it can be really important to show popups on click rather than on mouseover; or (b) this issue is reopened until it is actually solved. Actually, doing both of these would be best, but at least if the issue isn't solved it should not be marked closed.
This plugin is invaluable, and I thank you @bewithjonam very sincerely. But I pretty much gave up on it being able to support my needs until I stumbled on this hack, so appreciation to both of you for helping me get to the bottom of it.
